apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: politicni-portret
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: politicni-portret
    newName: rg.fr-par.scw.cloud/djnd/politicni-portret
    newTag: "latest"
